# How to run this? -> docker-compose -f docker-compose_v2.yml up
# Clean up? -> docker-compose -f docker-compose_v2.yml down --volumes
version: '3'

services:
  sauce_connect:
    image: saucelabs/sauce-connect
    environment:
      - SAUCE_USERNAME=${SAUCE_USERNAME}
      - SAUCE_ACCESS_KEY=${SAUCE_ACCESS_KEY}
    command: --tunnel-identifier python-tests -f /tmp/sc.ready
    volumes:
      - sauce-connect-volume:/tmp

  todo_app:
    image: todo_app
    ports:
      - "3000:3000"

  python_tests:
    image: python_tests
    environment:
      - SAUCE_USERNAME=${SAUCE_USERNAME}
      - SAUCE_ACCESS_KEY=${SAUCE_ACCESS_KEY}
      - SUT_HOST=todo_app
      - SAUCE_TUNNEL_NAME=python-tests
    volumes:
      - sauce-connect-volume:/tmp

volumes:
  sauce-connect-volume: